In [ ]:
# Step 1: Tokenize the texts and convert them into sequences of word indices
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
print(texts)
print(sequences)

['This is a positive review.', 'I really enjoyed this movie.', 'What a waste of time.', 'The acting was terrible.', 'The plot was captivating.', 'The movie was fantastic!', 'It was just okay.']
[[3, 6, 4, 7, 8], [9, 10, 11, 3, 5], [12, 4, 13, 14, 15], [2, 16, 1, 17], [2, 18, 1, 19], [2, 5, 1, 20], [21, 1, 22, 23]]


# New Section

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# Sample text data and corresponding labels (replace this with your own dataset)
texts = [
    "This is a positive review.",
    "I really enjoyed this movie.",
    "What a waste of time.",
    "The acting was terrible.",
    "The plot was captivating.",
    "The movie was fantastic!",
    "It was just okay."
]

labels = ['positive', 'positive', 'negative', 'negative', 'positive', 'positive', 'neutral']

# Step 1: Tokenize the texts and convert them into sequences of word indices
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

# Step 2: Pad the sequences to make them of equal length (required for neural networks)
max_sequence_length = max(len(seq) for seq in sequences)
padded_sequences = pad_sequences(sequences, maxlen=max_sequence_length)

# Step 3: Convert labels into numerical format
label_encoder = LabelEncoder()
label_encoder.fit(labels)
encoded_labels = label_encoder.transform(labels)
num_classes = len(np.unique(encoded_labels))
one_hot_labels = to_categorical(encoded_labels, num_classes=num_classes)

# Step 4: Load GloVe word embeddings
embedding_index = {}
with open('/content/drive/MyDrive/Colab Notebooks/glove.6B.100d.txt', encoding='utf-8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        coefs = np.asarray(values[1:], dtype='float32')
        embedding_index[word] = coefs

# Step 5: Create the embedding matrix using GloVe word embeddings
embedding_dim = 100
 # Change this based on the chosen GloVe embeddings dimension
vocabulary_size = len(tokenizer.word_index) + 1
embedding_matrix = np.zeros((vocabulary_size, embedding_dim))
for word, i in tokenizer.word_index.items():
    embedding_vector = embedding_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

# Step 6: Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(
    padded_sequences, one_hot_labels, test_size=0.2, random_state=42
)

# Step 7: Build the LSTM model with pre-trained word embeddings
model = Sequential()
model.add(Embedding(vocabulary_size, embedding_dim, weights=[embedding_matrix],
                    input_length=max_sequence_length, trainable=False))
model.add(LSTM(128))
model.add(Dense(num_classes, activation='softmax'))

# Step 8: Compile and train the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=10, batch_size=16, validation_split=0.1)

# Step 9: Evaluate the model on the test set
loss, accuracy = model.evaluate(x_test, y_test)
print(f'Test accuracy: {accuracy * 100:.2f}%')

Epoch 1/10
1/1 [==============================] - 3s 3s/step - loss: 1.0186 - accuracy: 0.5000 - val_loss: 1.4082 - val_accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 67ms/step - loss: 0.8550 - accuracy: 0.7500 - val_loss: 1.6886 - val_accuracy: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 0s 70ms/step - loss: 0.7234 - accuracy: 1.0000 - val_loss: 1.9789 - val_accuracy: 0.0000e+00
Epoch 4/10
1/1 [==============================] - 0s 68ms/step - loss: 0.6163 - accuracy: 1.0000 - val_loss: 2.2745 - val_accuracy: 0.0000e+00
Epoch 5/10
1/1 [==============================] - 0s 66ms/step - loss: 0.5274 - accuracy: 1.0000 - val_loss: 2.5714 - val_accuracy: 0.0000e+00
Epoch 6/10
1/1 [==============================] - 0s 71ms/step - loss: 0.4523 - accuracy: 1.0000 - val_loss: 2.8658 - val_accuracy: 0.0000e+00
Epoch 7/10
1/1 [==============================] - 0s 65ms/step - loss: 0.3877 - accuracy: 1.0000 - val_loss: 3.1545 - val_accuracy: 0.0000e+00
E

In [5]:
# Step 2: Pad the sequences to make them of equal length (required for neural networks)
max_sequence_length = max(len(seq) for seq in sequences)
padded_sequences = pad_sequences(sequences, maxlen=max_sequence_length)
print(padded_sequences)

[[ 3  6  4  7  8]
 [ 9 10 11  3  5]
 [12  4 13 14 15]
 [ 0  2 16  1 17]
 [ 0  2 18  1 19]
 [ 0  2  5  1 20]
 [ 0 21  1 22 23]]


In [4]:
# Step 3: Convert labels into numerical format
label_encoder = LabelEncoder()
label_encoder.fit(labels)
encoded_labels = label_encoder.transform(labels)
num_classes = len(np.unique(encoded_labels))
one_hot_labels = to_categorical(encoded_labels, num_classes=num_classes)
print(labels)
print(encoded_labels)
print(num_classes)
print(one_hot_labels)

['positive', 'positive', 'negative', 'negative', 'positive', 'positive', 'neutral']
[2 2 0 0 2 2 1]
3
[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [3]:
# Step 5: Create the embedding matrix using GloVe word embeddings
embedding_dim = 100  # Change this based on the chosen GloVe embeddings dimension
vocabulary_size = len(tokenizer.word_index) + 1
embedding_matrix = np.zeros((vocabulary_size, embedding_dim))
for word, i in tokenizer.word_index.items():
    embedding_vector = embedding_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector
print(vocabulary_size )
print(embedding_matrix )

24
[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.13717    -0.54286999  0.19419    ... -0.52056998  0.25433999
  -0.23759   ]
 [-0.038194   -0.24487001  0.72812003 ... -0.1459      0.82779998
   0.27061999]
 ...
 [-0.30664     0.16821     0.98510998 ... -0.38775     0.36916
   0.54521   ]
 [ 0.075026    0.39324999  0.90314001 ... -0.18816     0.46636
   0.66819   ]
 [ 0.066894    0.067771    0.67796999 ... -0.049597   -0.30153999
   0.21477   ]]
